services:
  fichart:
    image: jp8002/fichart:v0.1
    ports:
      - "8000:8000"

    volumes:
      - .:/djangoapp

    depends_on:
      - db
  
  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: